version: "3"
services:
  proxy:
    image: nginx:1.17.6
    ports:
      - "80:80"
    volumes:
      - ./etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./etc/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - app:app
  app:
    build: .
    expose:
      - "3000"
    ports:
      - "3000:3000"
